version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
      - '8501:8501'
    environment:
      - WHISPER_MODEL_SIZE=small
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2:1b
    command: ./start.sh
